### ISSUE TITLE
Change readme.md to be more informative of set_meetings command

### ISSUE THREAD

**Issue by nough** [juanfran/mattermost-gather-users#4]
I would suggest changing the set_meetings command info from: 
```
/gather-plugin set_meetings [{"user1": ["bruce", "martha"]}] - Set the meetings that have are already happened.
```

to
```
/gather-plugin set_meetings [{"user1": ["bruce", "martha"]}, {"user2":["alice","bob"]}, ...] - Set the meetings that have are already happened.
Note that "user1" is ignored, and is just used as a reference.
```

I believe that note is correct, from my understanding of the code - I don't understand Go well.

**Comment by juanfran** [comment]
Thanks! I think that I don't understand the note, "user1" is not ignored. This `{"user1": ["bruce", "martha"]}` means that user1 had met with bruce and alice.

**Comment by nough** [comment]
Ah, in that case it's useful to have the clarification, but it should be
written as
{"Alice": ["Bob", "Clara", ...]}, {"Bob": ["Alice", "Clara", ...]}, ...

This means:
Alice has met with Bob and Clara
Bob has met with Alice and Clara.

Also, what does your plugin do when there are an odd number of users?

**Comment by juanfran** [comment]
:+1: 

For an odd number of users there is a queue and each time one of the users in the queue does not have a meeting.
