### ISSUE TITLE
gather-users plugin reset itself and lost its list of members and previous meetings.

### ISSUE THREAD

**Issue by nough** [juanfran/mattermost-gather-users#5]
Afraid I don't know much about the process that this plugin uses to save data, but happy to help with troubleshooting. 

I've now reminded users to re-sign up, and have set at least two meetings to have already happened. I will update this issue with more information if the information is lost again. 

Is it possible that mattermost destroyed the plugin database?

**Comment by juanfran** [comment]
which version are you using? If you are using v1 upgrade to v2 to save the data. The code to restore the data is here https://github.com/juanfran/mattermost-gather-users/blob/master/server/activate.go, what caused the reset? Maybe if you upgraded mattermost the info was lost.

**Comment by nough** [comment]
I'm using v2.1. We haven't made any changes to the Mattermost server. It has once again lost the activated users, I think as an overnight thing.

Our servers are updated and restarted each night, but we upgraded the mattermost server itself manually, and that hasn't been performed recently (it's definitely not the cause of the plugin data loss).

**Comment by nough** [comment]
Mattermost.log has about 500 of these errors, although sometimes it's "app/status.go:213" or 238
`{"level":"warn","ts":1632986311.712406,"caller":"app/status.go:328","msg":"Failed to save status","user_id":"xxx","error":"failed in save Status: pq: duplicate key value violates unique constraint \"status_pkey\"","errorVerbose":"pq: duplicate key value violates unique constraint \"status_pkey\"
failed in save Status
github.com/mattermost/mattermost-server/v5/store/sqlstore.SqlStatusStore.SaveOrUpdate
     github.com/mattermost/mattermost-server/v5/store/sqlstore/status_store.go:50
github.com/mattermost/mattermost-server/v5/store/retrylayer.(*RetryLayerStatusStore).SaveOrUpdate
     github.com/mattermost/mattermost-server/v5/store/retrylayer/retrylayer.go:8303
github.com/mattermost/mattermost-server/v5/store/timerlayer.(*TimerLayerStatusStore).SaveOrUpdate
     github.com/mattermost/mattermost-server/v5/store/timerlayer/timerlayer.go:6894
github.com/mattermost/mattermost-server/v5/app.(*App).SaveAndBroadcastStatus
     github.com/mattermost/mattermost-server/v5/app/status.go:327
github.com/mattermost/mattermost-server/v5/app.(*App).SetStatusAwayIfNeeded
    github.com/mattermost/mattermost-server/v5/app/status.go:282
github.com/mattermost/mattermost-server/v5/app.(*WebConn).readPump.func2.1
    github.com/mattermost/mattermost-server/v5/app/web_conn.go:281
github.com/mattermost/mattermost-server/v5/app.(*Server).Go.func1
    github.com/mattermost/mattermost-server/v5/app/server.go:1133
runtime.goexit
    runtime/asm_amd64.s:1374"}`

**Comment by nough** [comment]
as a further update: The server did not restart last night, and therefore kept its memory of who was assigned to meetings etc.

So I'm under the impression that data stored in our keyvaluestore using kvset and kvget etc are lost when the server is restarted. Unfortunately the mattermost api documentation doesn't state whether this is intended or not.

**Comment by nough** [comment]
Alejandro Garcia has recommended checking the contents of the table PluginKeyValueStore in the database to see if the data is still there but unreachable.

https://community.mattermost.com/core/pl/xzp7ezr9f3y5dbb8bgs5ubk9ew

**Comment by juanfran** [comment]
I really don't know what it can be, sorry. 

One thing that can help is to restore the data manually. For example: 

```bash
// get the user list
/gather-plugin info

// restore users
/gather-plugin add @user6 @user7 @user8

// previous meetings
/gather-plugin meetings

// restore previous meetings
/gather-plugin set_meetings {"user4":["user3"],"user1":[],"user2":["user4","user3"],"user3":["user4","user2"]}
```

**Comment by nough** [comment]
That would only work if I had saved copies of the meetings and users before the server restarted, but yes it is an option.

**Comment by nough** [comment]
Update:

- I don't believe this has happened in the last six months
- We have updated the mattermost server in the last six months, so it has definitely restarted (and will have restarted several times).

**Comment by nough** [comment]
I'm going to close this issue.
