### ISSUE TITLE
Gather-plugin doesn't add all users to meetings

### ISSUE THREAD

**Issue by nough** [juanfran/mattermost-gather-users#6]
What it says on the tin. We've instantiated the gather-users plugin several times. Many users have had many meetings, but the plugin has only matched me once this whole time. Here is the output of `/gather-plugin meetings` with usernames obfuscated:
```
{"user1":["user21","user22","user7","user19","user17","user8","user11","user13","user10","user6","user18","user15","user20"],
"user2":[],
"user3":["user6","user12","user10","user15","user13","user17","user18","user19","user14","user7","user20"],
"user4":[],
"user5":[],
"user6":["user21","user7","user22","user10","user18","user8","user20","user1","user14","user9","user15"],
"user7":["user6","user8","user1","user9","user12","user14","user21","user19","user13","user15","user11"],
"user8":["user9","user19","user7","user12","user14","user18","user1","user6","user22","user13","user17"],
"user9":["user8","user17","user18","user7","user21","user13","user20","user19","user12","user6","user10"],
"user10":["user13","user14","user12","user6","user22","user18","user1","user20","user19","user21","user9"],
"user11":["user15","user1","user21","user14","user13","user17","user7","user22"],
"user12":["user20","user18","user22","user8","user10","user7","user17","user15","user21","user9","user14","user25","user19"],
"user13":["user15","user19","user10","user17","user20","user9","user1","user7","user11","user8","user22","user14"],
"user14":["user18","user15","user10","user20","user8","user7","user19","user22","user11","user6","user12","user13"],
"user15":["user13","user22","user14","user19","user17","user18","user11","user20","user12","user7","user21","user1","user6"],
"user16":["user19"],
"user17":["user22","user20","user9","user13","user15","user1","user12","user18","user11","user8","user21"],
"user18":["user14","user12","user20","user9","user21","user15","user8","user6","user10","user17","user22","user1","user19","user25"],
"user19":["user13","user8","user15","user1","user20","user21","user14","user7","user9","user10","user18","user12"],
"user20":["user12","user17","user18","user21","user14","user13","user19","user15","user9","user6","user10","user22","user1"],
"user21":["user1","user6","user20","user18","user22","user9","user19","user7","user11","user12","user15","user10","user17"],
"user22":["user17","user15","user1","user12","user6","user21","user10","user14","user8","user18","user20","user13","user11"],
"user23":["user10","user7"],
"user24":["user7","user1","user6","user19","user13","user9","user8","user10","user15","user17"]}
```

**Comment by juanfran** [comment]
Thanks!

Can you give me the output of this `/gather-plugin odd`

**Comment by nough** [comment]
Apologies for not giving it directly, but it's a list of 26 users in the form ["user1","user2",…,"user26"], except that the user names are not in alphabetical order.

I tried doing a `/gather-plugin off` followed by `/gather-plugin on`, which directly triggered a meeting for me. I then repeated `/gather-plugin odd` and the order and number of users listed was the same.

I am for example the 5th user in the oddturn list, but the 16th user in my comment above. However I did not receive a matching until I toggled my signup.
Another user who has had no meetings is #14 on the oddturn list, but is user2 in my comment above.

**Comment by juanfran** [comment]
I have published a new version https://github.com/juanfran/mattermost-gather-users/releases/tag/2.4.0, let me know if it fixes the issue.

Thanks!

**Comment by nough** [comment]
I've just updated today, I'll take a copy of the `/gather-plugin meetings` for today and another on Monday to check what's occuring.

**Comment by nough** [comment]
I think the new feature of actually showing whether a user is paused or not has resolved the issue! I checked with /gather-plugin info this morning, and the only users who didn't have a meeting were those who were set as paused. I've messaged each of them directly and I assume they'll get a meeting next monday.
