### ISSUE TITLE
Gather-plugin doesn't unpause users

### ISSUE THREAD

**Issue by nough** [juanfran/mattermost-gather-users#7]
We have Mattermost 5.0.4 installed, along with gather-users 2.4.0.

It seems that once a user is paused, they can't unpause themselves. I tested this several times myself, by typing /gather-users pause. This gave the message "Gather plugin unpaused" (never saying paused because it was still trying to unpause me), but each time when I checked ./gather-users info, I still showed up as paused.

Interestingly, if I then /gather-users off and /gather-users on, it will instantly match me up for a meeting, but /gather-users info will still show me as paused (and I imagine won't sign me up for a meeting the next week).

**Comment by juanfran** [comment]
Can you see if there is in the logs something like "Failed to serialize paused" or "Failed to persist paused"?

Have you tried with other users? 

Maybe the paused storage is corrupted with an old user reference, but I have no idea how it happened. One workaround that I can do is make two new commands for administrators, pause/unpause other users or clean the pause storage. But first tell if you see something in the server logs.

**Comment by nough** [comment]
Thanks for the quick response.
The mattermost.log file did not contain any instances of the word "paused". Would there be an alternative logfile where this would be stored?

As an update, I tried the command again this afternoon and it worked just fine. I asked another user who was paused to do it (they repeated several times), and they got:
unpaused
unpaused
paused
unpaused (and starts alternating as per expected behaviour).

a third user then had normal behaviour from the start.

I'm not sure if I should close this for bein frivolous, or if we should wait to see if the issue recurs (i.e. next monday when the plugin should match us up).

**Comment by juanfran** [comment]
No, there is no alternative log. I tried in two different instances with the plugin, and I was unable to reproduce the issue. So let me know if you find out something new, or you want me to add for administrators to being able to pause/unpause other users or clean the pause storage.

**Comment by nough** [comment]
Not seen any recurrence of this issue.
